import Head from 'next/head'
import Image from 'next/image'
import { SyntheticEvent } from 'react'
import { eventTracker } from '../hooks/useClickEvent'
import styles from '../styles/Home.module.css'

export default function Home() {
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.landing}>
        <div className={styles.grid}>
          <h1 className={styles.title}>
            Welcome to&nbsp;Today
          </h1>
          <a 
            onClick={(e: React.MouseEvent) => {eventTracker({tag: `${e.target.href}-${e.target.dataset.tag}`, type: 'click'})}}
            href="#dashboard" 
            className={styles.card}
            data-tag='button'
          >
            Enter Now
          </a>
        </div>
        <a 
          onClick={(e: React.MouseEvent) => {eventTracker({tag: `${e.target.href}-${e.target.dataset.tag}`, type: 'click'})}}
          href="#dashboard" 
          className={styles.description + ' landing-arrow'}
          data-tag='arrow'
        >
          &darr;
        </a>
      </div>
      <main id="dashboard" className={styles.main}>

        <h1 className={styles.title}>Test Complete</h1>
        <p className={styles.description}>Thank you</p>
      </main>

      <footer id="footer" className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="https://crislombardo.com/img/alligator.png" alt="Crickey Cris" width={72} height={36} />
          </span>
        </a>
      </footer>
    </div>
  )
}
